# Basic NumPy exercises

## Here you can find some basic Numpy exercises to practice your NumPy skills.

### Exercise 1: Matrix Manipulation

##### Create a 3x3 matrix with  random integer values between 1 and 10. Then, change all the even values to 0.

In [52]:
import numpy as np

In [53]:
matrix = np.random.randint( low = 1, high = 11, size = (3, 3))
matrix

array([[1, 1, 7],
       [6, 6, 7],
       [3, 5, 8]])

In [54]:
matrix[matrix % 2 == 0] = 0
print(matrix)

[[1 1 7]
 [0 0 7]
 [3 5 0]]


### Exercise 2: Statistics and Data Manipulation

##### Generate two 4x4 matrices with random integer numbers between 1 and 20. Find the maximum value in one matrix and the minimum value in the other matrix, then calculate the sum of these two values.


In [55]:
A = np.random.randint(low = 1, high = 21, size = (4, 4) )
B = np.random.randint(low = 1, high = 21, size = (4, 4) )

print("Matrix A: \n\n", A)

print("Matrix B: \n\n", B)



Matrix A: 

 [[ 5  8  2  9]
 [11 14 18  1]
 [16 14 16 17]
 [10 14 20  8]]
Matrix B: 

 [[15 10 16 19]
 [ 5 15  6  9]
 [20  7 20  4]
 [15  1  6 13]]


In [56]:
print("A max value:", A.max())
print("B max value:", B.max())
print("Sum:", A.max() + B.max())

A max value: 20
B max value: 20
Sum: 40


### Exercise 3: Operations and Slicing

##### Create a 5x5 matrix with random integer values between 1 and 100. Perform the following operations:

##### - Find the sum of all elements in the matrix.
##### - Calculate the mean of each row.
##### - Obtain the second column of the matrix and calculate its mean.

In [57]:
matrix = np.random.randint(low = 1, high = 101, size = (5, 5))
print(matrix)

[[76 83 88 62 45]
 [28 37 72 25 33]
 [79  2 80  5 16]
 [29 59 55 73 29]
 [ 6 14 80 72 60]]


In [58]:
print("Sum of all matrix elements:", matrix.sum())

Sum of all matrix elements: 1208


In [59]:
print("Mean of each row:", matrix.mean( axis = 1))

Mean of each row: [70.8 39.  36.4 49.  46.4]


In [60]:
second_column = matrix[:, 1]
print(second_column)

[83 37  2 59 14]


In [61]:
print("Second column mean: ", second_column.mean())

Second column mean:  39.0


### Exercise 4: Broadcasting and Reshaping

##### Create two matrices: one of size (3, 3) and another of size (3, 1). Perform the addition operation between these two matrices using broadcasting.

In [62]:
matrix_1 = np.random.randint(low= 0, high = 11, size = (3, 3))
print(matrix_1)
print("")

matrix_2 = np.random.randint(low= 0, high = 11, size = (3, 1))
print(matrix_2)
print("")

print(matrix_1 + matrix_2)


[[ 1  2  5]
 [ 5  0  7]
 [10  3  8]]

[[4]
 [6]
 [1]]

[[ 5  6  9]
 [11  6 13]
 [11  4  9]]


### Exercise 5: Custom Functions and Filtering

##### Create a 6x6 matrix with random integers between 1 and 50. Then, define a function that returns True if a number is prime and False otherwise. Apply this function to all elements of the matrix and filter out the prime numbers.

In [63]:
matrix = np.random.randint(low = 1, high = 51, size = (6, 6))
print(matrix)


[[33 17 38 12 11  1]
 [12  2 20 19  4 45]
 [ 1  6 41 44 10  2]
 [20 48 43 45  3 28]
 [46 10 40 11 19 50]
 [38 21 18 30  8 25]]


In [64]:
def is_prime(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

In [65]:
is_prime_vectorized = np.vectorize(is_prime)

print(matrix[is_prime_vectorized(matrix)])


[17 11  2 19 41  2 43  3 11 19]
