# NumPy Basics Notebook

### In this notebook you can find some basic knowledge about the NumPy library.


In [3]:
import numpy as np

np_array = np.array([[7, 77, 777], [8,88,888], [8,88,888]]) # I Create an ndarray with this function, 1 dimension, n-dimentions
#Its a multidemensional array

print(type(np_array))

<class 'numpy.ndarray'>


In [4]:

# I print array's shape(form)

print(type(np_array.shape)) # tuple is a list, but inmutable

print(np_array.shape) # 2 rows and 3 columns
print(np_array)

<class 'tuple'>
(3, 3)
[[  7  77 777]
 [  8  88 888]
 [  8  88 888]]


In [5]:
print(np_array[0][0])
print(np_array[0][1])
print(np_array[0][2])

print(np_array[1][0])
print(np_array[1][1])
print(np_array[1][2])

np_array[0][0] = 1203

print(np_array[0][0])

#Its the same as python list


7
77
777
8
88
888
1203


In [6]:
# Important for 3 dimensions array, 1 dimension = arrays, 2 = rows, 3= columns


np_array2 = np.array([[33,21,55],[67,82,12],[74,12,37]])

print("The shape of np_array2 its: ", np_array2.shape)
print(np_array2)
# Its a matris

The shape of np_array2 its:  (3, 3)
[[33 21 55]
 [67 82 12]
 [74 12 37]]


<img src = "https://i0.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1">


## Ways to create ndarrays


In [7]:
# ZEROS METHOD

ej1 = np.zeros((1080,1920))# 1080 array with 1920 elements, we are doing an HD img, also its 1080 rows and 1920 columns
#zeros method creates an array full of zeros


print(ej1)

print("")
print("-----------------")
print("")
ej1 = np.zeros((5,3))
print(ej1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

-----------------

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# FULL METHOD

ej2 = np.full((2,2), "python") # This method fills with a number an ndarray, firs parameter its ndarray's shape and the second one its
# the number/element
print(ej2)

print("")
print("")
print("")

ej2 = np.full((2,2), 35.3) 
print(ej2)

print("")
print("")
print("")

ej2 = np.full((2,3,4), 8 )
print(ej2)

[['python' 'python']
 ['python' 'python']]



[[35.3 35.3]
 [35.3 35.3]]



[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]


In [9]:
# EYE METHOD

ej3 = np.eye(5,5) # creates an ndarray with an diagonal of 1
print(ej3)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#ONES METHOD

ej4 = np.ones((3,5,2)) #Creates a nparray or matrix filled with ones
print(ej4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [11]:
# CREATE A MATRIZ FILLED WITH RAMDOM FLOAT VALUES

ej5 = np.random.random((5,5))
print(ej5)

[[0.8313341  0.19244653 0.9328585  0.16264002 0.52606739]
 [0.69072789 0.76241787 0.9738432  0.61141115 0.93973138]
 [0.00844336 0.70691601 0.68538172 0.59679641 0.75895468]
 [0.85638411 0.33431299 0.09202494 0.39138849 0.45155538]
 [0.87221225 0.07221786 0.32931405 0.17658629 0.24596662]]


## Array of indexes

### Sometimes it is useful to make arrays with the indexes that interest me from another array, in order to operate on them.


In [12]:
array_a = np.array([[11,22,33], [25, 37,98], [12,34,12], [51,21,54]])
print(array_a)
print(array_a.shape)

[[11 22 33]
 [25 37 98]
 [12 34 12]
 [51 21 54]]
(4, 3)


In [13]:
rows = np.arange(4)
cols = np.array([0,1,2,0])
print("These are rows indexes -> ", rows)
print("These are columns indexes ->", cols)



These are rows indexes ->  [0 1 2 3]
These are columns indexes -> [0 1 2 0]


In [14]:
for row,col in zip(rows, cols): # zip merge two arrays un tuples
    print("(", row,",", col, ")")

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [15]:
print("The values that are in these indexes are:",array_a[rows, cols])

The values that are in these indexes are: [11 37 12 51]


In [16]:
print(array_a)
print("\n\n")

array_a += 10 
print(array_a)

print("\n\n")
array_a[rows, cols] += 1000
print(array_a)

[[11 22 33]
 [25 37 98]
 [12 34 12]
 [51 21 54]]



[[ 21  32  43]
 [ 35  47 108]
 [ 22  44  22]
 [ 61  31  64]]



[[1021   32   43]
 [  35 1047  108]
 [  22   44 1022]
 [1061   31   64]]


## Boolean Index
### We can use conditionals or "filters" to modify and operate the elements of a ndarray

In [17]:
# Array 3x2
array_b = np.array([[11, 12],[21,22], [31,32]])
print(array_b)
print("------------")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
------------
(3, 2)


In [18]:
#Create a filter 

filter = array_b > 21
print(filter)
print(type(filter))

# filter generates a new matrix, in this matrix the elements that were greater than 15 will be true, the other will be false

[[False False]
 [False  True]
 [ True  True]]
<class 'numpy.ndarray'>


In [19]:
filtered = array_b[filter]

print(filtered)

[22 31 32]


In [20]:
# a Faster way to apply the filter

print(array_b[array_b % 2 == 0])

[12 22 32]


### The main use of these filters  its to allows us to modify some of the values of the array that meet certain conditions

In [21]:
array_b[(array_b %2 == 0)] += 10000

print(array_b)

[[   11 10012]
 [   21 10022]
 [   31 10032]]


## Slicing arrays (slice)
#### we can get a slice of an array, it is like separate a sub-region

In [22]:
x_array = np.array([[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
print(x_array)

slice_array = x_array[0:2,1:3] # El primer par de valores representa la fila, se toma la fila del 0 al 2, el segundo paramentro es del
# 1 al 3 en las columnas
print("")
print(slice_array)


[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]

[[12 13]
 [22 23]]


In [23]:
slice_array[0][0] += 100
print(slice_array)
print("")

print(x_array)

# Here we can see that a slice isnt an independet array, its a pointer, so if we modify some value in the slice in fact 
#we are modifying the main matrix



[[112  13]
 [ 22  23]]

[[ 11 112  13  14  15]
 [ 21  22  23  24  25]
 [ 31  32  33  34  35]
 [ 41  42  43  44  45]]


In [24]:
# We can transform a slice into a independent array

new_array = np.array(slice_array)
new_array += 1000


print(new_array)

print("")

print(x_array)

[[1112 1013]
 [1022 1023]]

[[ 11 112  13  14  15]
 [ 21  22  23  24  25]
 [ 31  32  33  34  35]
 [ 41  42  43  44  45]]


In [25]:
print("")
print(x_array[1, :])

print("")
print(x_array[:3, 2:])


[21 22 23 24 25]

[[13 14 15]
 [23 24 25]
 [33 34 35]]


## Type of data at numpy arrays


In [26]:
# when Its created an ndarray numpy detects the type of data

ej1 = np.array([11,12])
print(ej1.dtype)

int32


In [27]:
ej2 = np.array([11.2, 11.3])
print(ej2.dtype)

float64


In [28]:
ej3 = np.array([11,11.2])
print(ej3.dtype)

float64


In [29]:
ej4 = np.array(["numpy", 3, 3.0])
print(ej4.dtype)

<U32


In [30]:
# It can be forced some data type 

ej5 = np.array([3,4], dtype = np.float64)
print(ej5.dtype)

float64


In [31]:
ej6 = np.array([3.2,5.2], dtype = np.int32)
print(ej6.dtype)
print("")
print(ej6)

int32

[3 5]



## Aritmetic Operations

In [32]:
# We can do operation between arrays that have the same shape

x = np.array([[1, 2], [3, 4]], dtype = np.int64)
y = np.array([[1, 1], [2,3]], dtype = np.int64)

In [33]:
#sum

print(x + y)

[[2 3]
 [5 7]]


In [34]:
#subtraction

print(x - y)

[[0 1]
 [1 1]]


In [35]:
# multiplication

print(x *y)

[[ 1  2]
 [ 6 12]]


In [36]:
#pow

print(x**y)

[[ 1  2]
 [ 9 64]]


In [37]:
# division

print(x/y)

[[1.         2.        ]
 [1.5        1.33333333]]


## Basic Statistical Operations

In [38]:
# Create an array with random numbers in a range

arr = 10 * np.random.randn(2,5)
print(arr)

stats_array = np.array([[10,9, 8, 7], [3, 2, 1, 0], [5, 4, 6, 5]])

[[-10.19290514  16.10895901  -2.86164007  -9.54118377   7.44051743]
 [  0.94809885  32.58453715  15.68787059  -2.88634236   3.684666  ]]


In [86]:
## Get max and min value

print("Max value:", stats_array.max())
print("Min value:", stats_array.min())

Max value: 10
Min value: 0


In [39]:
#calculate mean(media)

print(stats_array.mean())

5.0


In [40]:
#calculate mean froam an specific row
# IMPORTANT

# axis 0 = columns
# axis 1 = rows
print(stats_array.mean( axis = 1 )) # This gonna print 3 mean because therea are 3 rows


print(stats_array.mean(axis = 0))

[8.5 1.5 5. ]
[6. 5. 5. 4.]


In [41]:
# Rows mean
print(stats_array.mean( axis = 1 )) 
print( "")

print(stats_array[0, :].mean())
print(stats_array[1, :].mean())
print(stats_array[2, :].mean())

[8.5 1.5 5. ]

8.5
1.5
5.0


In [42]:
#Columns mean

print(stats_array.mean( axis = 0 )) 
print( "")

print(stats_array[:, 0].mean())
print(stats_array[:, 1].mean())
print(stats_array[:, 2].mean())
print(stats_array[:, 3].mean())

[6. 5. 5. 4.]

6.0
5.0
5.0
4.0


In [43]:
#With this its created an array witn 10 random numbers

messy_array = np.random.randn(10)
print(type(messy_array))
print(messy_array)

<class 'numpy.ndarray'>
[-0.9885148   0.34798198  0.32037298 -0.64042731  0.78713079  1.09744795
  0.32284877  0.03411751  1.33481028  0.80280254]


In [44]:
# With sort() i sort the numbers of the array

sorted_array = np.array(messy_array)
sorted_array.sort()
print(sorted_array)



[-0.9885148  -0.64042731  0.03411751  0.32037298  0.32284877  0.34798198
  0.78713079  0.80280254  1.09744795  1.33481028]


In [45]:
## Searching unique elements in the array( VERY USEFUL)

array = np.array([1,2 , 1, 3, 1, 2, 2, 3, 3, 4])
print(np.unique(array))

[1 2 3 4]


In [46]:
s1 = np.array(["table",  "chair","window"])
s2 = np.array(["table",  "chair","lamp"])

In [47]:
#intersection

print(np.intersect1d(s1, s2))

['escritorio' 'silla']


In [48]:
# Union
print(np.union1d(s1, s2))

['escritorio' 'lampara' 'mesa' 'silla']


In [49]:
#elements that there isnt in s2 of s1

print(np.setdiff1d(s1, s2))

print("")
#elements that there isnt in s1 of s2
print(np.setdiff1d(s2, s1))

['mesa']

['lampara']


In [50]:
# Elements from s1 that there are in s2

print(np.in1d(s1, s2))

[ True  True False]


## Frecuent Operations


In [51]:
# Sum all the elements from an array

sum_array = np.array([[1,2,3], [4,3,9]])

print(sum_array.sum())
print(sum_array[:,:].sum())

22
22


In [81]:
# np.argwhere, find indexes that comply with an contidional

ex1 = np.array([1,2, 1, 0, 0, 0, 3, 0, 5, 1, 0])

np.argwhere(ex1 != 0)


array([[ 3],
       [ 4],
       [ 5],
       [ 7],
       [10]], dtype=int64)

In [82]:
np.argwhere(ex1 == 0)

array([[ 3],
       [ 4],
       [ 5],
       [ 7],
       [10]], dtype=int64)

In [53]:
# Sum rows

print(np.sum(sum_array, axis = 1))

print(sum_array[0, :].sum())
print(sum_array[1, :].sum())

# Sum columns

print(np.sum(sum_array, axis = 0))
print(sum_array[:, 0].sum())
print(sum_array[:, 1].sum())
print(sum_array[:, 2].sum())



[ 6 16]
6
16
[ 5  5 12]
5
5
12


## Vectorize a function (np.vectorize)

### np.vectorize converts a normal python function(operating on scalars) into a function that can operate on NumPy arrays element by element

In [95]:
# if a number is prime this funcition will return true, otherwise
# will return false
def is_prime(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

In [96]:
matrix  = np.arange(10)
print(matrix)

[0 1 2 3 4 5 6 7 8 9]


In [97]:
# if we use this function in a matrix it will generate an error
is_prime(matrix)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
is_prime_vectorized = np.vectorize(is_prime)
print(is_prime_vectorized(matrix))

print(matrix[is_prime_vectorized(matrix)])

[False False  True  True False  True False  True False False]
[2 3 5 7]


## Reform an array

In [99]:
arr = np.arange(20)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(20,)

In [100]:
# Its changed its shape

reshped_arr = arr.reshape(4, 5)
print(reshped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [101]:
reshped_arr = arr.reshape(2, 5, 2)
print(reshped_arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


# transposing an array

#### Transportation exchanges rows with columns 

In [102]:
ex1 = np.array([[11, 12], [21, 22]])
print(ex1)
ex1.T



[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [103]:
ex1 = np.array([[11, 12, 4, 5], [21, 22, 6, 7]])
print(ex1)
ex1.T


[[11 12  4  5]
 [21 22  6  7]]


array([[11, 21],
       [12, 22],
       [ 4,  6],
       [ 5,  7]])

In [104]:
ex2 = np.array([[11, 12, 13, 14, 15], [21, 22, 23, 24, 25], [31, 32, 33, 34, 35], [41, 42, 43, 44, 45] ,[51, 52, 53, 54, 55]])
print(ex2)
ex2.T
# Reflect it

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


array([[11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]])

In [105]:
# WHERE, (VERY USEFUUUUL)
mat = np.random.randn(4, 4)
mat

array([[ 0.78268359,  1.98915253,  0.51255201, -0.91747811],
       [ 0.2105304 ,  0.47528792,  0.42863698, -0.41927152],
       [ 1.98514003,  1.63325704, -0.33943288,  0.26879637],
       [ 0.88530238,  0.24173535,  1.5032002 ,  0.08106186]])

In [106]:
np.where( mat > 0.5, 1000, 0)

# firs argument its the conditional, all the values that comply with the contiditios will remplaced with second argument, 
# otherwise, will be remplaced with the third argument


array([[1000, 1000, 1000,    0],
       [   0,    0,    0,    0],
       [1000, 1000,    0,    0],
       [1000,    0, 1000,    0]])

In [62]:
# Check if any of the values its true or false

arr_bools = np.array([0, 0 , 0 , 0 ,0 ])

arr_bools.any()



False

In [63]:
# Any number that isnt 0 its considered true
arr_bools = np.array([0, 0 , 0 , 0 ,1 ])

arr_bools.any()

True

In [64]:

arr_bools = np.array([0, 0 , 0 , 0 , True ])

arr_bools.any()

True

In [65]:

arr_bools = np.array([0, 0 , 0 , 0 ,False ])

arr_bools.any()

False

In [66]:
# Any number that isnt 0 its considered true
arr_bools = np.array([0, 0 , 0 , 0 ,5 ])

arr_bools.any()

True

In [67]:
# Check if all the elemnts are true

arr_bools = np.array([1, 1 , 2 ])
arr_bools.all()

True

In [68]:

arr_bools = np.array([1, 1 , 0 ])
arr_bools.all()

False

## Meging data sets

In [69]:
array_k = np.random.randint(low = 2, high = 50, size = (2, 2)) # randint return random integers
# Ramdon matrix wich lower its 2 and highter 50 and its shape its 2 x 2
print(array_k)
print("")
array_m = np.random.randint(low = 2, high = 50, size = (2, 2)) 
print(array_m)

[[30 21]
 [ 7 49]]

[[49 36]
 [ 8 43]]


In [70]:
np.vstack((array_k , array_m)) # This stack verticaly two arrays

array([[30, 21],
       [ 7, 49],
       [49, 36],
       [ 8, 43]])

In [71]:
np.hstack((array_k , array_m)) # This stack horizotaly two arrays

array([[30, 21, 49, 36],
       [ 7, 49,  8, 43]])

In [72]:
# concatenate, the same result as np.vstack
np.concatenate([array_k, array_m], axis = 0)

array([[30, 21],
       [ 7, 49],
       [49, 36],
       [ 8, 43]])

In [73]:
np.concatenate([array_k, array_m], axis = 1)

array([[30, 21, 49, 36],
       [ 7, 49,  8, 43]])

## Broadcasting


Para más detalles: 
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [74]:
base = np.zeros((5, 5))

print(base)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [75]:
# Propagation with rows
row = np.array([1, 2, 3, 4, 5])

print(row)
print("")

print(base +row)

[1 2 3 4 5]

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [76]:
# Propagation with columns

column = np.array([[10, 20 ,30 , 40 , 50]])

print(column) # this is a row

print("")

column = column.T
print(column)

print("")

print( base + column)

[[10 20 30 40 50]]

[[10]
 [20]
 [30]
 [40]
 [50]]

[[10. 10. 10. 10. 10.]
 [20. 20. 20. 20. 20.]
 [30. 30. 30. 30. 30.]
 [40. 40. 40. 40. 40.]
 [50. 50. 50. 50. 50.]]


In [77]:
# With one element

one = np.array([1])
print(base + one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Save arrays in disc / load array form disc

In [78]:
x = np.array([22, 23, 24])

In [79]:
np.save('array_importante.npy', x)

In [ ]:
old_array = np.load('array_impotant.npy')

In [84]:
matriz_r = np.random.randn(3, 3, 3)
print(matriz_r)

[[[ 0.87598599  0.42444647 -0.03759558]
  [ 0.00540827 -0.59433873  0.61771148]
  [-0.11720367 -0.10302732  0.15200499]]

 [[-0.87829937 -0.03281092  0.84253138]
  [-0.01142067  0.78989797 -1.56322421]
  [ 0.42979955  1.58947095  0.43182237]]

 [[ 0.04975303  0.1159695   0.88549538]
  [ 0.57789202 -0.94908658 -0.39564466]
  [-0.12192654 -0.56276897  0.28289819]]]
